### ISSUE TITLE
Blur only the widget child and not the background

### ISSUE THREAD

**Issue by Near0ne** [jagritjkh/blur#1]
Hi ! :)
First of all, thank you for your awesome plugin !
I have a question
I have a specific widget, a bar chart with a transparent background, and i want to make it blurry.
Things that i succeed with your plugin, but saddly, it also blurred everything behind it, such as my view background image.
Can you tell me please how to blur only the widget and not things behind it ? 
Thank you !

![example](https://user-images.githubusercontent.com/8754117/97725882-f8854200-1ace-11eb-9c6e-5af6b628399d.jpg)

**Comment by jagritjkh** [comment]
Hi!, Thank you that you liked it!
So, you have to blur each of the bars separately. You have to wrap each bar separately with the Blur wrapper widget to blur them and then you can give them overlay widget (the text on them).

**Comment by Near0ne** [comment]
Hi ! :)
Thank you for your quick answer !
Sorry for the delay.
So, i understand what do you mean by far, and i tried it, but i cant afford to achieve this because the chart is the whole widget, and these bars aren't widgets... (From FL chart, they are equatable mixin)
I even try to extend them, but equatable mixin (the bars, i don't understand what they are) are not widgets, so it doesn't work with your plugin...
That's why i think, the solution i was searching for, is to know if it's possible to blur only the current widget (here the chart) and not the parents widget such the scaffold etc.
Because my chart has a transparent background

Thank you for your future answer !

![5g2yn3b7](https://user-images.githubusercontent.com/8754117/97849962-a7a26300-1cf3-11eb-984e-f0ac1b24fe5c.png)
