### ISSUE TITLE
Animated bluring

### ISSUE THREAD

**Issue by pro100svitlo** [jagritjkh/blur#3]
Is there a way to do the blurring/frosting with animation?
With duration and curve, etc

**Comment by jagritjkh** [comment]
Working on it.
Will update it soon!

**Comment by jagritjkh** [comment]
Hey, currently working on code reduction, if you want to animate blurring, you can use the following code for now:-

 late AnimationController controller;
  late CurvedAnimation animation;

  @override
  void initState() {
    super.initState();
    controller = AnimationController(
      duration: Duration(milliseconds: 400),
      vsync: this,
    )..addListener(() {
        setState(() {});
      });
    animation = CurvedAnimation(parent: controller, curve: Curves.decelerate);
    controller.forward();
  }

  @override
  Widget build(BuildContext context) {
    return Blur(
      child: child,
      blur: animation.value,
      blurColor: blurColor,
    );
  }
  
  Just add animation controller and curved animation and use value of curved animation as blur value.
  And for increasing the time increase the duration of the animation controller.
  
  Still, if you want me to add this to the package just drop a comment.
  Thank you, Jagrit!

**Comment by jagritjkh** [comment]
Added in the repository, but will remove later.
Use package like this:-
 blur:
    git:
      url: https://github.com/jagritjkh/blur.git

**Comment by pro100svitlo** [comment]
I already implemented that in my project :)
So there is no rush. I just was wondered that it is not available out of the box. That's why I left this issue here 😄

**Comment by jagritjkh** [comment]
Oh ok, but if it is available out of the box, then I won't be able to give the full customization around the widget. I can only give the customizable duration of the animation and curve. Though, I will think about it.
Thank you!
