### ISSUE TITLE
performance issue when using Blur as an image item in ListView.builder

### ISSUE THREAD

**Issue by AgungLaksana** [jagritjkh/blur#4]
Hi, I am using Blur widget as an item of my ListView.builder . it makes my app laggy even in release mode. here is the code below I use for Blur. is there a workaround for this?

```
Blur(
            blur: 2,
            child: CachedNetworkImage(
              imageUrl: thumbnailURL,
              fit: BoxFit.fill,
              height: double.infinity,
              width: double.infinity,
              fadeInCurve: Curves.easeIn,
              fadeInDuration: const Duration(milliseconds: 100),
            ),
          ),
```

**Comment by jagritjkh** [comment]
Hey, it's not because of Blur, it's because of CachedNetworkImage. I have used cached network image in various projects which feels laggy, still, if you think it's because of blur, kindly drop a comment.
